### ISSUE TITLE
Usage without a Rimworld install?

### ISSUE THREAD

**Issue by RobRoseKnows** [zzzz465/rwxml-language-server#7]
Hey, I really like this tool, it looks super useful and I can't wait to try it out. I was wondering though if you ever considered adding functionality for it without a Rimworld install present. That way someone could mod in a lightweight environment like GitHub Codespaces without needing to have Rimworld installed on the system they're modding on. Obviously it probably wouldn't be able to do reflection on modded defs and such, but it could probably at least support vanilla defs.

**Comment by zzzz465** [comment]
unfortunately, in order to use this plugin, you need a complete installation of rimworld.
if we bundle vanilla defs data then it's possible to implement that.
it would be nice if it supports that feature. but right now I don't think I can spend time on this project.

I'll try to support that feature. also, PR is always open!

**Comment by RobRoseKnows** [comment]
Do you think we could use the Krafs.Rimworld.Ref NuGet package? It has reference assemblies for vanilla Rimworld.

**Comment by zzzz465** [comment]
even with that reference it still needs rimworld core xml.

**Comment by zzzz465** [comment]
I might rewrite this with rust.

**Comment by RobRoseKnows** [comment]
Yeah I might write a similar tool. Rust would be cool, though I don't know how well it interacts with C#.

**Comment by RobRoseKnows** [comment]
It looks like this XML Server already supports XML catalogs and schemas: https://github.com/redhat-developer/vscode-xml

If we wrote a tool to generate schemas from the Rimworld XML, we could use another language server.

**Comment by zzzz465** [comment]
I researched about using xml schema to validate documentations...
using schema has potentials, but It only provides basic type checking like string, number, object, etc...
any advanced feature like referencing, or type checking based on structure is not supported I guess.

currently I'm started re-writing some prototype due to technical debt of my current code.

**Comment by zzzz465** [comment]
@RobRoseKnows 
I'm bit worried about LICENSE of using rimworld data, and files. so I asked tynan about that.
unfortunately, third-party distribution is not allowed. it cannot be shipped with this plugin. 

the project still gets dependent to installed RimWorld on the client's computer.
